export const USER_GROUPS = {
  SUPER_ADMIN: 'super_admin',
  ORGANIZATION_ADMIN: 'organization_admin',
  COUNTRY_ADMIN: 'country_admin',
  CLINIC_ADMIN: 'clinic_admin',
  THERAPIST_ADMIN: 'therapist_admin',
  TRANSLATOR: 'translator',
  PATIENT: 'patient'
};

export const USER_ROLES = {
  ORGANIZATION_ADMIN: 'organization_admin',
  GLOBAL_ADMIN: 'global_admin',
  COUNTRY_ADMIN: 'country_admin',
  CLINIC_ADMIN: 'clinic_admin',
  MANAGE_ORGANIZATION_ADMIN: 'manage_organization_admin',
  MANAGE_GLOBAL_ADMIN: 'manage_global_admin',
  MANAGE_COUNTRY_ADMIN: 'manage_country_admin',
  MANAGE_CLINIC_ADMIN: 'manage_clinic_admin',
  MANAGE_THERAPIST: 'manage_therapist',
  MANAGE_PATIENT: 'manage_patient',
  SETUP_CATEGORY: 'setup_category',
  SETUP_EXERCISE: 'setup_exercise',
  SETUP_EDUCATIONAL_MATERIAL: 'setup_educational_material',
  SETUP_QUESTIONNAIRE: 'setup_questionnaire',
  VIEW_REPORT: 'view_report',
  VIEW_TREATMENT_DETAIL: 'view_treatment_detail',
  VIEW_APPOINTMENT: 'view_appointment',
  ARRANGE_APPOINTMENT: 'arrange_appointment',
  CREATE_TREATMENT_PLAN_FOR_PATIENT: 'create_treatment_plan_for_patient',
  VIEW_EXERCISE: 'view_exercise',
  VIEW_EDUCATIONAL_MATERIAL: 'view_educational_material',
  VIEW_QUESTIONNAIRE: 'view_questionnaire',
  SUBMIT_EXERCISE_RESULT: 'submit_exercise_result',
  SUBMIT_QUESTIONNAIRE_ANSWER: 'submit_questionnaire_answer',
  VIEW_GOAL_PROGRESS: 'view_goal_progress',
  INPUT_GOAL_PROGRESS: 'input_goal_progress',
  MESSAGE_CALL_BETWEEN_THERAPIST_PATIENT: 'message_call_between_therapist_patient',
  VIEW_EDIT_OWN_PROFILE: 'view_edit_own_profile',
  MANAGE_ORGANIZATION: 'manage_organization',
  MANAGE_ASSISTIVE_TECHNOLOGY: 'manage_assistive_technology',
  MANAGE_COUNTRY: 'manage_country',
  MANAGE_TRANSLATION: 'manage_translation',
  MANAGE_SYSTEM_LIMIT: 'manage_system_limit',
  MANAGE_TERM_CONDITION: 'manage_term_condition',
  MANAGE_PRIVACY_POLICY: 'manage_privacy_policy',
  MANAGE_CLINIC: 'manage_clinic',
  MANAGE_PROFESSION: 'manage_profession',
  MANAGE_LANGUAGE: 'manage_language',
  MANAGE_STATIC_PAGE: 'manage_static_page',
  MANAGE_GUIDANCE_PAGE: 'manage_guidance_page',
  MANAGE_DISEASE: 'manage_disease',
  VIEW_TERM_CONDITION: 'view_term_condition',
  VIEW_PRIVACY_POLICY: 'view_privacy_policy',
  MANAGE_COLOR_SCHEME: 'manage_color_scheme',
  MANAGE_TRANSLATOR: 'manage_translator',
  TRANSLATE_TRANSLATION: 'translate_translation',
  TRANSLATE_EDUCATIONAL_MATERIAL: 'translate_educational_material',
  TRANSLATE_EXERCISE: 'translate_exercise',
  TRANSLATE_QUESTIONNAIRE: 'translate_questionnaire',
  TRANSLATE_GUIDANCE_PAGE: 'translate_guidance_page',
  TRANSLATE_PRIVACY_POLICY: 'translate_privacy_policy',
  TRANSLATE_STATIC_PAGE: 'translate_static_page',
  TRANSLATE_TERM_CONDITION: 'translate_term_condition',
  TRANSLATE_CATEGORY: 'translate_category',
  TRANSLATE_ASSISTIVE_TECHNOLOGY: 'translate_assistive_technology',
  VIEW_DASHBOARD: 'view_dashboard',
  SUPER_ADMIN: 'super_admin',
  MANAGE_SURVEY: 'manage_survey',
  DOWNLOAD_SURVEY: 'download_survey',
  MANAGE_HEALTH_CONDITION: 'manage_health_condition',
  MANAGE_MFA_POLICY: 'manage_mfa_policy'
};

export const SETTING_ROLES = [
  USER_ROLES.MANAGE_COUNTRY,
  USER_ROLES.MANAGE_LANGUAGE,
  USER_ROLES.MANAGE_TRANSLATION,
  USER_ROLES.MANAGE_SYSTEM_LIMIT,
  USER_ROLES.MANAGE_CLINIC,
  USER_ROLES.MANAGE_PROFESSION,
  USER_ROLES.MANAGE_STATIC_PAGE,
  USER_ROLES.MANAGE_TERM_CONDITION,
  USER_ROLES.MANAGE_PRIVACY_POLICY,
  USER_ROLES.MANAGE_GUIDANCE_PAGE,
  USER_ROLES.MANAGE_ORGANIZATION,
  USER_ROLES.TRANSLATE_TRANSLATION,
  USER_ROLES.TRANSLATE_STATIC_PAGE,
  USER_ROLES.TRANSLATE_PRIVACY_POLICY,
  USER_ROLES.TRANSLATE_GUIDANCE_PAGE,
  USER_ROLES.MANAGE_SURVEY,
  USER_ROLES.MANAGE_HEALTH_CONDITION
];
